name: "test"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up JDK 17
          uses: actions/setup-java@v2.5.0
          with:
            distribution: 'adopt'
            java-version: '17'
            java-package: jdk
            architecture: x64
      - name: Build artifacts
        run: ./gradlew build
